title: My Blog
author: Thanawat Polcharoen
email: thanawat.pcr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog at Github pages

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: ThanawatP # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
